FROM node:8.12.0-slim
# FROM node:13.6.0-slim

MAINTAINER devops@wastebox.biz

WORKDIR /home/node/app

COPY package*.json /home/node/app/

RUN npm install

# RUN apt-get update && apt-get install -y curl
RUN /bin/sh -c 'curl https://install.meteor.com/ | sh'

COPY ./ /home/node/app

# RUN [ "mkdir", "-p", "/home/node/app/input_img/" ]
# RUN [ "mkdir", "-p", "/home/node/app/output_img/" ]
RUN mkdir -p /home/node/app/input_img/ /home/node/app/output_img/

## tried to dynamically add ip to /etc/hosts during build
## failed because the changes are not persisted, but temporary containers are deleted
## fix: extra_hosts in docker-compose file
# RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && apt-get install -y iproute2 
# RUN ip -4 route list match 0/0 | awk '{print $3" host.docker.internal"}' >> /etc/hosts;cat /etc/hosts
## CMD ip -4 route list match 0/0 | awk '{print $3" host.docker.internal"}' >> /etc/hosts;cat /etc/hosts

EXPOSE 3000
EXPOSE 3001

# RUN meteor update --patch --allow-superuser
RUN meteor update --all-packages --allow-superuser

CMD [ "npm", "start" ]
#RUN meteor --settings settings.json --production
